[2022-08-02 13:51:49,623] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: Demo.records_saving manual__2022-08-02T13:51:34.386490+00:00 [queued]>
[2022-08-02 13:51:49,634] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: Demo.records_saving manual__2022-08-02T13:51:34.386490+00:00 [queued]>
[2022-08-02 13:51:49,634] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-08-02 13:51:49,635] {taskinstance.py:1377} INFO - Starting attempt 1 of 1
[2022-08-02 13:51:49,636] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-08-02 13:51:49,653] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): records_saving> on 2022-08-02 13:51:34.386490+00:00
[2022-08-02 13:51:49,658] {standard_task_runner.py:52} INFO - Started process 12854 to run task
[2022-08-02 13:51:49,661] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'Demo', 'records_saving', 'manual__2022-08-02T13:51:34.386490+00:00', '--job-id', '311', '--raw', '--subdir', 'DAGS_FOLDER/demo.py', '--cfg-path', '/tmp/tmpdcku8tgl', '--error-file', '/tmp/tmpp2pr8o9b']
[2022-08-02 13:51:49,662] {standard_task_runner.py:80} INFO - Job 311: Subtask records_saving
[2022-08-02 13:51:49,737] {task_command.py:371} INFO - Running <TaskInstance: Demo.records_saving manual__2022-08-02T13:51:34.386490+00:00 [running]> on host 31353b71d6cb
[2022-08-02 13:51:49,827] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=Demo
AIRFLOW_CTX_TASK_ID=records_saving
AIRFLOW_CTX_EXECUTION_DATE=2022-08-02T13:51:34.386490+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-08-02T13:51:34.386490+00:00
[2022-08-02 13:51:49,829] {python.py:173} INFO - Done. Returned value was: 0
[2022-08-02 13:51:49,861] {taskinstance.py:1420} INFO - Marking task as SUCCESS. dag_id=Demo, task_id=records_saving, execution_date=20220802T135134, start_date=20220802T135149, end_date=20220802T135149
[2022-08-02 13:51:49,913] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-08-02 13:51:49,955] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
