[2022-08-02 10:01:49,388] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: Demo.records_saving manual__2022-08-02T10:01:26.637553+00:00 [queued]>
[2022-08-02 10:01:49,417] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: Demo.records_saving manual__2022-08-02T10:01:26.637553+00:00 [queued]>
[2022-08-02 10:01:49,417] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-08-02 10:01:49,418] {taskinstance.py:1377} INFO - Starting attempt 1 of 1
[2022-08-02 10:01:49,455] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-08-02 10:01:49,500] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): records_saving> on 2022-08-02 10:01:26.637553+00:00
[2022-08-02 10:01:49,508] {standard_task_runner.py:52} INFO - Started process 4120 to run task
[2022-08-02 10:01:49,515] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'Demo', 'records_saving', 'manual__2022-08-02T10:01:26.637553+00:00', '--job-id', '207', '--raw', '--subdir', 'DAGS_FOLDER/demo.py', '--cfg-path', '/tmp/tmp1aw_wtkr', '--error-file', '/tmp/tmp6ml4_x7r']
[2022-08-02 10:01:49,517] {standard_task_runner.py:80} INFO - Job 207: Subtask records_saving
[2022-08-02 10:01:49,694] {task_command.py:371} INFO - Running <TaskInstance: Demo.records_saving manual__2022-08-02T10:01:26.637553+00:00 [running]> on host 31353b71d6cb
[2022-08-02 10:01:49,907] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=Demo
AIRFLOW_CTX_TASK_ID=records_saving
AIRFLOW_CTX_EXECUTION_DATE=2022-08-02T10:01:26.637553+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-08-02T10:01:26.637553+00:00
[2022-08-02 10:01:49,930] {base.py:68} INFO - Using connection ID 'postgres_demo' for task execution.
[2022-08-02 10:01:49,938] {dbapi.py:231} INFO - Running statement: CREATE TABLE IF NOT EXISTS public."Files"
                            (
                                id integer NOT NULL,
                                name character(80)[] COLLATE pg_catalog."default" NOT NULL,
                                size bigint,
                                CONSTRAINT "Files_pkey" PRIMARY KEY (id)
                            ), parameters: None
[2022-08-02 10:01:49,955] {base.py:68} INFO - Using connection ID 'postgres_demo' for task execution.
[2022-08-02 10:01:49,962] {dbapi.py:231} INFO - Running statement: INSERT INTO public."Files"(
                                id, name, size)
                                VALUES (%()s, %()s, %()s);, parameters: {'id': 0, 'name': 'houssem', 'size': 100}
[2022-08-02 10:01:49,963] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/demo.py", line 62, in save_records
    VALUES (%()s, %()s, %()s);""",parameters={"id":i,"name":"houssem","size":i+100})
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/dbapi.py", line 211, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/dbapi.py", line 233, in _run_command
    cur.execute(sql_statement, parameters)
KeyError: ''
[2022-08-02 10:01:49,987] {taskinstance.py:1420} INFO - Marking task as FAILED. dag_id=Demo, task_id=records_saving, execution_date=20220802T100126, start_date=20220802T100149, end_date=20220802T100149
[2022-08-02 10:01:50,019] {standard_task_runner.py:97} ERROR - Failed to execute job 207 for task records_saving (''; 4120)
[2022-08-02 10:01:50,049] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-08-02 10:01:50,234] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
